from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(hotels)
admin.site.register(Guide)
admin.site.register(restaurant_bars)
admin.site.register(food)
admin.site.register(sitestouristiques)
admin.site.register(event)
admin.site.register(lieux_de_loisirs)
admin.site.register(province)
admin.site.register(quartiers)
admin.site.register(churches)
admin.site.register(market)
admin.site.register(hospitals)
admin.site.register(Tendance)
admin.site.register(Information)
admin.site.register(transport)
admin.site.register(culture)
admin.site.register(photo)
admin.site.register(art)
admin.site.register(conference)
admin.site.register(PageView)
admin.site.register(view_guide)
admin.site.register(view_art)
admin.site.register(view_hotel)
admin.site.register(view_restaurant_bars)
admin.site.register(view_food)
admin.site.register(view_conference)
admin.site.register(view_event)
admin.site.register(view_churches)
admin.site.register(view_sitestouristiques)
admin.site.register(view_market)
admin.site.register(view_lieux_de_loisirs)
admin.site.register(view_province)
admin.site.register(view_quartiers)
admin.site.register(view_hospital)
admin.site.register(view_nightclubs)
admin.site.register(view_culture)
